#!/usr/bin/env python3
"""
Export a downstream-ready project reference bundle.

Creates exports/project-reference/ containing:
- AGENTS.reference.md
- references.link-only.yaml
- policies/ (copied from repository)
- indexes/ (copied from repository)

Does NOT copy sources/upstream/ or acquisition/.
"""

import os
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required.", file=sys.stderr)
    print("Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


AGENTS_REFERENCE_CONTENT = """\
# AGENTS.reference.md

This file is generated by the bio-agent-reference-pack export tool.

## Authority

- Downstream project instructions override this pack.
- References are link-only unless explicitly acquired later.
- Agents must read upstream official URLs before using guidance.
- Indexes are routing aids only.
- No scientific summaries are included.
- This export contains no upstream source files.
"""

RENAME_FIELDS = {"id": "source_id"}
ALLOWED_FIELDS = {"source_id", "title", "source_type", "upstream", "license", "notes"}


def find_repo_root():
    path = Path(__file__).resolve().parent.parent
    if not (path / "references.yaml").exists():
        print("ERROR: Cannot find repository root (references.yaml not found).", file=sys.stderr)
        sys.exit(1)
    return path


def load_yaml(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def write_yaml(path, data):
    os.makedirs(path.parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def select_reviewed_link_only(entries):
    selected = []
    for entry in entries:
        if (
            entry.get("status") == "reviewed"
            and entry.get("acquisition_mode") == "link_only"
            and entry.get("upstream") is not None
        ):
            selected.append(entry)
    return selected


def build_catalog_entry(entry):
    catalog_entry = {}
    for key, value in entry.items():
        new_key = RENAME_FIELDS.get(key, key)
        if new_key in ALLOWED_FIELDS:
            catalog_entry[new_key] = value
    return catalog_entry


def copy_directory_contents(src_dir, dst_dir):
    os.makedirs(dst_dir, exist_ok=True)
    for item in sorted(src_dir.iterdir()):
        if item.is_file():
            shutil.copy2(item, dst_dir / item.name)


def export_project_reference(repo_root=None):
    if repo_root is None:
        repo_root = find_repo_root()

    refs_path = repo_root / "references.yaml"
    data = load_yaml(refs_path)
    entries = data.get("entries", [])

    selected = select_reviewed_link_only(entries)

    errors = []
    for entry in selected:
        source_id = entry.get("id", "unknown")
        if entry.get("local_path") is not None:
            errors.append(f"Entry '{source_id}' has local_path set.")
        if entry.get("version") is not None:
            errors.append(f"Entry '{source_id}' has version set.")
    if errors:
        for err in errors:
            print(f"ERROR: {err}", file=sys.stderr)
        sys.exit(1)

    catalog_entries = [build_catalog_entry(e) for e in selected]
    link_only_data = {
        "schema_version": "0.1",
        "description": (
            "Link-only reference catalog for downstream projects. "
            "Entries link to upstream official URLs. "
            "No source content has been acquired."
        ),
        "entries": catalog_entries,
    }

    export_dir = repo_root / "exports" / "project-reference"

    # Clean previous export if exists
    if export_dir.exists():
        shutil.rmtree(export_dir)

    os.makedirs(export_dir, exist_ok=True)

    # Write AGENTS.reference.md
    agents_path = export_dir / "AGENTS.reference.md"
    with open(agents_path, "w", encoding="utf-8") as f:
        f.write(AGENTS_REFERENCE_CONTENT)

    # Write references.link-only.yaml
    refs_export_path = export_dir / "references.link-only.yaml"
    write_yaml(refs_export_path, link_only_data)

    # Copy policies/
    policies_src = repo_root / "policies"
    policies_dst = export_dir / "policies"
    if policies_src.exists():
        copy_directory_contents(policies_src, policies_dst)

    # Copy indexes/
    indexes_src = repo_root / "indexes"
    indexes_dst = export_dir / "indexes"
    if indexes_src.exists():
        copy_directory_contents(indexes_src, indexes_dst)

    # Print summary
    print("Exported project reference bundle to exports/project-reference/")
    print(f"  - AGENTS.reference.md")
    print(f"  - references.link-only.yaml ({len(catalog_entries)} entries)")
    print(f"  - policies/ ({len(list(export_dir.joinpath('policies').iterdir()))} files)")
    print(f"  - indexes/ ({len(list(export_dir.joinpath('indexes').iterdir()))} files)")

    return export_dir


def main():
    export_project_reference()


if __name__ == "__main__":
    main()
